CREATE TABLE [dbo].[weather] (

	[cod] varchar(8000) NULL, 
	[message] bigint NULL, 
	[cnt] bigint NULL, 
	[list.dt] bigint NULL, 
	[list.main.temp] float NULL, 
	[list.main.feels_like] float NULL, 
	[list.main.temp_min] float NULL, 
	[list.main.temp_max] float NULL, 
	[list.main.pressure] bigint NULL, 
	[list.main.sea_level] bigint NULL, 
	[list.main.grnd_level] bigint NULL, 
	[list.main.humidity] bigint NULL, 
	[list.main.temp_kf] float NULL, 
	[list.weather.id] bigint NULL, 
	[list.weather.main] varchar(8000) NULL, 
	[list.weather.description] varchar(8000) NULL, 
	[list.weather.icon] varchar(8000) NULL, 
	[list.clouds.all] bigint NULL, 
	[list.wind.speed] float NULL, 
	[list.wind.deg] bigint NULL, 
	[list.wind.gust] float NULL, 
	[list.visibility] bigint NULL, 
	[list.pop] float NULL, 
	[list.rain.3h] float NULL, 
	[list.sys.pod] varchar(8000) NULL, 
	[list.dt_txt] varchar(8000) NULL, 
	[city.id] bigint NULL, 
	[city.name] varchar(8000) NULL, 
	[city.coord.lat] float NULL, 
	[city.coord.lon] float NULL, 
	[city.country] varchar(8000) NULL, 
	[city.population] bigint NULL, 
	[city.timezone] bigint NULL, 
	[city.sunrise] bigint NULL, 
	[city.sunset] bigint NULL
);