table Orders
	lineageTag: bfc3cad3-9ef7-41d1-9884-e1ebcffdafcf

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 4ebaaddd-ac55-49a7-89fa-ea58651c9b55
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 4bbe1a8f-843f-447d-8bad-0a5a718bb6d4
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b575b1cd-1466-4b99-b26b-50aeaf443960
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: f8f1aaef-bee0-4028-9a76-0dcfe6db19f7
			defaultHierarchy: LocalDateTable_a112de6d-4274-40ef-835a-ab6719ea60a5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d2531649-7419-46a3-a000-9a735f0783f4
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: dc8ca565-81e1-4593-8009-6195c833bb22
			defaultHierarchy: LocalDateTable_f0378d4c-342a-4d3f-bfd8-4fc6cdea3769.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: a19cea3a-0d44-41ad-9816-a5c640b97afc
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: f8e6869b-d933-43b2-a854-970087f510bd
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: e7dd6e15-7f9b-4ab0-b6d5-09715c4eae9e
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: da0e7b3e-e292-4a8c-9ee3-18b3b904d019
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 8aa1511e-f565-4d01-a470-ebf1aa76ba7c
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: b4e29ba9-52db-4741-ab3f-96ca39207a0a
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: bde3d0c6-40bd-49fe-ad1c-7e94d78b3f6f
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: fe069f30-d221-48d8-9ba5-7985570232b4
		summarizeBy: count
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 541e885b-8727-45db-ae7d-3971ac766e59
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 9af07369-78e7-464b-99b5-99347763a23c
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: a8f7d922-698a-4dcc-9c95-92677f89806c
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: dc02f828-4d2d-40ce-a53c-171ed3be3e43
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: b4734442-dffd-4da3-a140-e6c41387268c
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: d1974e40-dedc-473f-afca-aeeb838eb26a
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 83d355f7-4d53-46cf-9ca1-63dcf6efc591
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: fa7e638f-75a2-4766-a696-7abf0751902a
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: c030404f-e972-48c1-abca-c1b840011dad
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Orders-73178eba-f7a4-43e5-85e6-bedc5089dd8b = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Analytics With Nag\Internshala\Power BI DAX Material - Youtube\Section 1\Superstore.xlsx"), null, true),
				    Orders_Sheet = Source{[Item="Orders",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Orders_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country", type text}, {"City", type text}, {"State", type text}, {"Postal Code", Int64.Type}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

