table People
	lineageTag: 6dcb1f14-f906-45ab-8ab0-98035b2013c9

	column Person
		dataType: string
		lineageTag: e24c699c-a46c-43d4-b97a-95b8dad7ad1c
		summarizeBy: none
		sourceColumn: Person

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 998856b4-0e6c-45d4-8585-f7fffe18228d
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition People-60164467-bd4c-47d6-b709-ece5fb44fefa = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Analytics With Nag\Internshala\Power BI DAX Material - Youtube\Section 1\Superstore.xlsx"), null, true),
				    People_Sheet = Source{[Item="People",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(People_Sheet,{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Person", type text}, {"Region", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

