table Returns
	lineageTag: bb01b673-1672-444e-aad4-54232bb5148e

	column Returned
		dataType: string
		lineageTag: 33587cf6-c988-4424-aaae-d10907da5da1
		summarizeBy: none
		sourceColumn: Returned

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 313bc931-9aa3-4734-b2b6-355b950abc34
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	partition Returns-d93e7e90-526b-4720-91be-96624f4dda83 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Analytics With Nag\Internshala\Power BI DAX Material - Youtube\Section 1\Superstore.xlsx"), null, true),
				    Returns_Sheet = Source{[Item="Returns",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Returns_Sheet,{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Returned", type text}, {"Order ID", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

