table Sheet3
	lineageTag: d163448b-10ea-470e-a22a-779ca3cb655f

	column Country
		dataType: string
		lineageTag: 79d641ef-bb5a-42f7-8350-4f4eb5c2d580
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 74a6d683-6be3-41c6-be2c-7de53ad3a95d
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	partition Sheet3 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\rgane\Downloads\Deloitte Ques 08_2024.xlsx"), null, true),
				    Sheet3_Sheet = Source{[Item="Sheet3",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Sheet3_Sheet,{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Country", type text}, {"City", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

