table Sheet2
	lineageTag: fc52f7b1-ef98-4de1-9f13-e35db75454a0

	column Country
		dataType: string
		lineageTag: 87115d21-8a27-42f0-ac5c-61b9903529a8
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 9580e545-8c7a-4e30-91d8-0f30c1f84d2f
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Transactions
		dataType: string
		lineageTag: 570d50cc-9857-444e-84a1-af4427de0517
		summarizeBy: none
		sourceColumn: Transactions

		annotation SummarizationSetBy = Automatic

	partition Sheet2 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\rgane\Downloads\Deloitte Ques 08_2024.xlsx"), null, true),
				    Sheet2_Sheet = Source{[Item="Sheet2",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Sheet2_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Country", type text}, {"City", type text}, {"Transactions", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

